
def help1():
    l1 = ["Why did Little Red Riding Hood's mother give Little Red Riding Hood a basket of treats?",
        "Why did Little Red Riding Hood's mother tell Little Red Riding Hood not to talk to strangers?",
        "Why did Little Red Riding Hood talk to the wolf?",
        "Why did the wolf ask Little Red Riding Hood what she was doing in the forest?",
        "Why did the wolf dress as Little Red Riding Hood's grandmother?",
        "Why did the wolf go to Little Red Riding Hood's grandmother's house?",
        "Why did the wolf pretend to be Little Red Riding Hood's grandmother?",
        "Why does Little Red Riding Hood say to the wolf \"What big eyes you have?\"",
        "Why does Little Red Riding Hood say to the wolf \"What big ears you have?\"",
        "Why does Little Red Riding Hood say to the wolf \"What big teeth you have?\"",
        "Why does the wolf want to eat Little Red Riding Hood?",
        "Why does the wolf put Little Red Riding Hood's grandmother in the closet?",
        "Why does the lumberjack help Little Red Riding Hood?",
        "Why doesn't the lumberjack kill the wolf?",
        "Why is the wolf so bad?",
        "Why couldn't Little Red Riding Hood's grandmother stop the wolf?",
        "How come the wolf can talk?",
        "Why didn't the wolf eat Little Red Riding Hood's grandmother?",
        "Are all strangers bad?",
        "Can grown-ups talk to strangers?",
        "Why is it bad to talk to strangers?",
        "How did the wolf know where Little Red Riding Hood's grandmother's house is?",
        "Why did Little Red Riding Hood realize the lesson at the end of the story?",
        "Why did Little Red Riding Hood go into the woods alone?",
        "Why didn't the grandmother cry for help?",
        "Why did the grandmother think the wolf was Little Red Riding Hood?",
        "Is this story true?"]
    l2 = [
        "To give to her grandmother.",
        "Because she thought there might be bad strangers in the woods.",
        "She forgot what her mother told her about not talking to strangers.",
        "So he could find out where she was going.",
        "To trick Little Red Riding Hood into thinking he was her grandmother.",
        "So he could eat Little Red Riding Hood and her grandmother.",
        "To trick Little Red Riding Hood to coming closer to him so he could get her.",
        "Because the wolf's eyes didn't look like her grandmother's eyes.",
        "Because the wolf's ears didn't look like her grandmother's ears.",
        "Because the wolf's teeth didn't look like her grandmother's teeth.",
        "Because the wolf likes to eat people.",
        "To keep her hidden until Little Red Riding Hood arrives.",
        "He wants to save her from the wolf.",
        "The lumberjack just wants to save Little Red Riding Hood. He doesn't want to hurt the wolf.",
        "He is bad because he wants to hurt Little Red Riding Hood and her grandmother.",
        "The wolf is much stronger than Little Red Riding Hood's grandmother.",
        "This is a story and in some stories, animals can talk.",
        "The wolf didn't have enough time to eat the grandmother before Little Red Riding Hood arrived.",
        "Not all strangers are bad.   But it can be hard for a child to tell a good stranger from a bad stranger.",
        "Grown-ups sometimes talk to strangers.  But they are still careful about which strangers they talk to.",
        "You shouldn't talk to people you don't know because some strangers may try to hurt you.",
        "The wolf lives in the woods, so he knows where the houses are.",
        "She saw what happens when she talked to a stranger.",
        "This was the way to get to her grandmother's house.",
        "The wolf grabbed her too quickly.",
        "She was expecting only Little Red Riding Hood and no one else.",
        "The story is not true."]
    l3 = ["When people are sick, they often get treats.",
        "Parents tell kids not to do things, like talk to strangers, that could hurt them.",
        "Children often forget what their parents tell them.",
        "You ask people questions to get information from them.",
        "People put on disguises when they don't want others to know who they really are.",
        "People go to others' houses when they want what's in those houses. In this case, the wolf wanted to eat the grandmother.",
        "People pretend to be other people when they don't want others to know who they really are.",
        "People usually notice when someone looks differently than usual and then they say something about it.",
        "People usually notice when someone looks differently than usual and then they say something about it.",
        "People usually notice when someone looks differently than usual and then they say something about it.",
        "When wolves get hungry they want to eat something. In this case, it is Little Red Riding Hood.",
        "When you don't want someone to see something, you hide it.  The wolf didn't want Little Red Riding Hood to see the real grandmother.",
        "Good people always help people who are in trouble.",
        "Good people don't kill others.",
        "Stories often have bad characters in them that try to hurt other characters.",
        "Wolves are stronger than old women.",
        "Animals can often talk in stories even though they don't talk in real life.",
        "People usually don't do bad things in front of other.  The wolf didn't want to scare Little Red Riding Hood away.",
        "In real life, most strangers aren't bad, but we don't always know which ones are good and which are bad, so we have to be careful.",
        "Grown-ups sometimes talk to strangers when they need information, but they are careful which strangers they talk to.",
        "Some strangers are bad people like criminals and they use information they get from people to hurt them.",
        "People generally know where others live near to where they live.  Since the wolf and the grandmother live in the woods, the wolf knows where she lives.",
        "Generally, when something bad happens, people try to figure out why.  Little Red Riding Hood wanted to know why she had a bad experience with the wolf.",
        "Sometimes parents send children on errands by themselves.  They think that the children are old enough to be responsible.",
        "Sometimes people are so surprised by what happens that they don't have time to scream for help.  The wolf surprised the grandmother.",
        "When people are expecting someone to visit, they assume that when they hear a knock on the door, it is the person they are expecting.",
        "Fairy tales are not true.  They are used to teach a lesson."]
    l4 = ["Don't you like to eat good things when you are sick? Why do you like to do that?",
        "Don't your parents also tell you not to talk to strangers? Did they tell you why?",
        "Did you ever get distracted and forget what your parents told you?",
        "Has anyone tried to trick you before, so that person could do something bad?",
        "Think of people you've seen on TV who put on disguises to hide who they really are. Why do they do that?",
        "Have you seen a story or a movie where a bad guy goes to someone's house because he wants what's in the house?",
        "Have you seen a story or movie where a bad guy pretends to be a different person in order to trick someone?",
        "Did you ever say something when you noticed someone who looks different than usual?",
        "Did you ever say something when you noticed someone who looks different than usual?",
        "Did you ever say something when you noticed someone who looks different than usual?",
        "Have you read a story or seen a movie where a big animal or monster tries to eat a person? Why did it do that?",
        "If you wanted to take someone's place, what would you do with the real person?",
        "What do heros normally do when they see someone in danger?",
        "Think of superheros you've seen in the movies.  Do they kill the bad guys or just save the people in trouble?",
        "Think about other stories or movies you've seen.  Isn't there a bad guy in them a lot of the time?",
        "Think about how strong your grandmother is. Do you think she could stop a wolf?",
        "Have you seen other stories or movies that have talking animals?",
        "What happens when you don't have time to do something?  Don't you wait until later to do it?",
        "Think of strangers you've met.  Were some good and some bad?",
        "Grown-ups sometimes talk to strangers.  Think about which strangers you've seen your parents talk to.",
        "Have you ever met someone who you first thought was good, but the person turned out to be bad?",
        "The wolf lives in the woods like Little Red Riding Hood's grandmother. Don't you know where people live in your neighborhood, too?",
        "Have you ever had a bad thing happen to you and then you tried to learn why it happened?",
        "Have your parents ever sent you on an errand by yourself? What errand was that?",
        "Have you ever been so surprised by something that happened quickly that you didn't have time to scream?",
        "Have you ever seen a story or movie where someone fooled someone else by putting on a disguise?",
        "This story is like other fairy tales you've heard of that teach children lessons.  Fairy tales aren't true."]
    l5 = ["Because treats can help Little Red Riding Hood's grandmother feel better.",
        "To prevent Little Red Riding Hood from getting hurt by a bad stranger.",
        "Because she wanted to be friendly.",
        "He wanted to find out if she was alone, so he could eat her.  When he found out that she was going to her grandmother's house, he decided he could eat both of them.",
        "He wanted to trick her to think he was her grandmother so she wouldn't try to run away.",
        "He wanted to eat both Little Red Riding Hood and her grandmother at the same time.  He figured if he ate Little Red Riding Hood in the woods, her grandmother might get suspicious because it was taking too long for Little Red Riding Hood to arrive at her house.",
        "He wanted to trick her to think he was her grandmother so she wouldn't try to run away.",
        "She noticed that the wolf didn't look like her grandmother and wanted to find out why she was looking at big eyes instead of her grandmother's eyes.",
        "She noticed that the wolf didn't look like her grandmother and wanted to find out why she was looking at big ears instead of her grandmother's eyes.",
        "She noticed that the wolf didn't look like her grandmother and wanted to find out why she was looking at big teeth instead of her grandmother's eyes.",
        "The wolf wants to eat Little Red Riding Hood because he is hungry and also because the story has to show something bad happening when children talk to strangers.",
        "Because he doesn't have enough time to eat her before Little Red Riding Hood arrives and can't let Little Red Riding Hood see both the wolf and the grandmother together or she will run for help.",
        "He helps Little Red Riding Hood in order to save her and her mother's lives.",
        "Because the killing is wrong and the lumberjack doesn't want to do a bad thing just because the wolf wanted to do a bad thing.",
        "The wolf is bad so that the story can show how talking to strangers can lead to bad things.",
        "She couldn't stop the wolf because if she did, then the story wouldn't be able to teach children not to talk to strangers.",
        "The wolf has to be able to talk so he can find out where Little Red Riding Hood's grandmother lives.",
        "The wolf doesn't have enough time to eat the grandmother before Little Red Riding Hood arrives and if she sees him trying to eat her grandmother, she'll run away and the wolf won't get her.",
        "All strangers aren't bad, but some are.  This story needs a bad stranger in it to show how if children talk to strangers, bad things can happen.",
        "Grown ups talk to strangers, but they need to be careful which strangers they talk to because bad things can happen to grown ups who talk to strangers, too.",
        "If the stranger is a bad person, he or she might use the infromation you give him to hurt you.",
        "The wolf has to know where the grandmother's house is.  Otherwise, the rest of the story doesn't make sense since the wolf wouldn't get to the grandmother's house.",
        "By realizing the lesson not to talk to strangers, Little Red Riding Hood helps other children learn the lesson, too.",
        "She had to go through the woods in order to get to her grandmother's house.",
        "The wolf grabbed her so quickly that she didn't have time to scream.",
        "The grandmother was expecting only Little Red Riding Hood to come, so she didn't expect any one else to come to her house.",
        "The story isn't true, but it is seems like it could be true to help children understand why it's bad to talk to strangers."]

    o = []
    for i in range(len(l1)):
        tmp = []
        tmp.append(l1[i])
        tmp.append(l2[i])
        tmp.append(l3[i])
        tmp.append(l4[i])
        tmp.append(l5[i])
        o.append(tmp)
    return o


def help2(s = ""):
    l1 = ["Why did Little Red Riding Hood's mother give Little Red Riding Hood a basket of treats?",
        "Why did Little Red Riding Hood's mother tell Little Red Riding Hood not to talk to strangers?",
        "Why did Little Red Riding Hood talk to the wolf?",
        "Why did the wolf ask Little Red Riding Hood what she was doing in the forest?",
        "Why did the wolf dress as Little Red Riding Hood's grandmother?",
        "Why did the wolf go to Little Red Riding Hood's grandmother's house?",
        "Why did the wolf pretend to be Little Red Riding Hood's grandmother?",
        "Why does Little Red Riding Hood say to the wolf \"What big eyes you have?\"",
        "Why does Little Red Riding Hood say to the wolf \"What big ears you have?\"",
        "Why does Little Red Riding Hood say to the wolf \"What big teeth you have?\"",
        "Why does the wolf want to eat Little Red Riding Hood?",
        "Why does the wolf put Little Red Riding Hood's grandmother in the closet?",
        "Why does the lumberjack help Little Red Riding Hood?",
        "Why doesn't the lumberjack kill the wolf?",
        "Why is the wolf so bad?",
        "Why couldn't Little Red Riding Hood's grandmother stop the wolf?",
        "How come the wolf can talk?",
        "Why didn't the wolf eat Little Red Riding Hood's grandmother?",
        "Are all strangers bad?",
        "Can grown-ups talk to strangers?",
        "Why is it bad to talk to strangers?",
        "How did the wolf know where Little Red Riding Hood's grandmother's house is?",
        "Why did Little Red Riding Hood realize the lesson at the end of the story?",
        "Why did Little Red Riding Hood go into the woods alone?",
        "Why didn't the grandmother cry for help?",
        "Why did the grandmother think the wolf was Little Red Riding Hood?",
        "Is this story true?"]
    l2 = [
        "To give to her grandmother.",
        "Because she thought there might be bad strangers in the woods.",
        "She forgot what her mother told her about not talking to strangers.",
        "So he could find out where she was going.",
        "To trick Little Red Riding Hood into thinking he was her grandmother.",
        "So he could eat Little Red Riding Hood and her grandmother.",
        "To trick Little Red Riding Hood to coming closer to him so he could get her.",
        "Because the wolf's eyes didn't look like her grandmother's eyes.",
        "Because the wolf's ears didn't look like her grandmother's ears.",
        "Because the wolf's teeth didn't look like her grandmother's teeth.",
        "Because the wolf likes to eat people.",
        "To keep her hidden until Little Red Riding Hood arrives.",
        "He wants to save her from the wolf.",
        "The lumberjack just wants to save Little Red Riding Hood. He doesn't want to hurt the wolf.",
        "He is bad because he wants to hurt Little Red Riding Hood and her grandmother.",
        "The wolf is much stronger than Little Red Riding Hood's grandmother.",
        "This is a story and in some stories, animals can talk.",
        "The wolf didn't have enough time to eat the grandmother before Little Red Riding Hood arrived.",
        "Not all strangers are bad.   But it can be hard for a child to tell a good stranger from a bad stranger.",
        "Grown-ups sometimes talk to strangers.  But they are still careful about which strangers they talk to.",
        "You shouldn't talk to people you don't know because some strangers may try to hurt you.",
        "The wolf lives in the woods, so he knows where the houses are.",
        "She saw what happens when she talked to a stranger.",
        "This was the way to get to her grandmother's house.",
        "The wolf grabbed her too quickly.",
        "She was expecting only Little Red Riding Hood and no one else.",
        "The story is not true."]
    l3 = ["When people are sick, they often get treats.",
        "Parents tell kids not to do things, like talk to strangers, that could hurt them.",
        "Children often forget what their parents tell them.",
        "You ask people questions to get information from them.",
        "People put on disguises when they don't want others to know who they really are.",
        "People go to others' houses when they want what's in those houses. In this case, the wolf wanted to eat the grandmother.",
        "People pretend to be other people when they don't want others to know who they really are.",
        "People usually notice when someone looks differently than usual and then they say something about it.",
        "People usually notice when someone looks differently than usual and then they say something about it.",
        "People usually notice when someone looks differently than usual and then they say something about it.",
        "When wolves get hungry they want to eat something. In this case, it is Little Red Riding Hood.",
        "When you don't want someone to see something, you hide it.  The wolf didn't want Little Red Riding Hood to see the real grandmother.",
        "Good people always help people who are in trouble.",
        "Good people don't kill others.",
        "Stories often have bad characters in them that try to hurt other characters.",
        "Wolves are stronger than old women.",
        "Animals can often talk in stories even though they don't talk in real life.",
        "People usually don't do bad things in front of other.  The wolf didn't want to scare Little Red Riding Hood away.",
        "In real life, most strangers aren't bad, but we don't always know which ones are good and which are bad, so we have to be careful.",
        "Grown-ups sometimes talk to strangers when they need information, but they are careful which strangers they talk to.",
        "Some strangers are bad people like criminals and they use information they get from people to hurt them.",
        "People generally know where others live near to where they live.  Since the wolf and the grandmother live in the woods, the wolf knows where she lives.",
        "Generally, when something bad happens, people try to figure out why.  Little Red Riding Hood wanted to know why she had a bad experience with the wolf.",
        "Sometimes parents send children on errands by themselves.  They think that the children are old enough to be responsible.",
        "Sometimes people are so surprised by what happens that they don't have time to scream for help.  The wolf surprised the grandmother.",
        "When people are expecting someone to visit, they assume that when they hear a knock on the door, it is the person they are expecting.",
        "Fairy tales are not true.  They are used to teach a lesson."]
    l4 = ["Don't you like to eat good things when you are sick? Why do you like to do that?",
        "Don't your parents also tell you not to talk to strangers? Did they tell you why?",
        "Did you ever get distracted and forget what your parents told you?",
        "Has anyone tried to trick you before, so that person could do something bad?",
        "Think of people you've seen on TV who put on disguises to hide who they really are. Why do they do that?",
        "Have you seen a story or a movie where a bad guy goes to someone's house because he wants what's in the house?",
        "Have you seen a story or movie where a bad guy pretends to be a different person in order to trick someone?",
        "Did you ever say something when you noticed someone who looks different than usual?",
        "Did you ever say something when you noticed someone who looks different than usual?",
        "Did you ever say something when you noticed someone who looks different than usual?",
        "Have you read a story or seen a movie where a big animal or monster tries to eat a person? Why did it do that?",
        "If you wanted to take someone's place, what would you do with the real person?",
        "What do heros normally do when they see someone in danger?",
        "Think of superheros you've seen in the movies.  Do they kill the bad guys or just save the people in trouble?",
        "Think about other stories or movies you've seen.  Isn't there a bad guy in them a lot of the time?",
        "Think about how strong your grandmother is. Do you think she could stop a wolf?",
        "Have you seen other stories or movies that have talking animals?",
        "What happens when you don't have time to do something?  Don't you wait until later to do it?",
        "Think of strangers you've met.  Were some good and some bad?",
        "Grown-ups sometimes talk to strangers.  Think about which strangers you've seen your parents talk to.",
        "Have you ever met someone who you first thought was good, but the person turned out to be bad?",
        "The wolf lives in the woods like Little Red Riding Hood's grandmother. Don't you know where people live in your neighborhood, too?",
        "Have you ever had a bad thing happen to you and then you tried to learn why it happened?",
        "Have your parents ever sent you on an errand by yourself? What errand was that?",
        "Have you ever been so surprised by something that happened quickly that you didn't have time to scream?",
        "Have you ever seen a story or movie where someone fooled someone else by putting on a disguise?",
        "This story is like other fairy tales you've heard of that teach children lessons.  Fairy tales aren't true."]
    l5 = ["Because treats can help Little Red Riding Hood's grandmother feel better.",
        "To prevent Little Red Riding Hood from getting hurt by a bad stranger.",
        "Because she wanted to be friendly.",
        "He wanted to find out if she was alone, so he could eat her.  When he found out that she was going to her grandmother's house, he decided he could eat both of them.",
        "He wanted to trick her to think he was her grandmother so she wouldn't try to run away.",
        "He wanted to eat both Little Red Riding Hood and her grandmother at the same time.  He figured if he ate Little Red Riding Hood in the woods, her grandmother might get suspicious because it was taking too long for Little Red Riding Hood to arrive at her house.",
        "He wanted to trick her to think he was her grandmother so she wouldn't try to run away.",
        "She noticed that the wolf didn't look like her grandmother and wanted to find out why she was looking at big eyes instead of her grandmother's eyes.",
        "She noticed that the wolf didn't look like her grandmother and wanted to find out why she was looking at big ears instead of her grandmother's eyes.",
        "She noticed that the wolf didn't look like her grandmother and wanted to find out why she was looking at big teeth instead of her grandmother's eyes.",
        "The wolf wants to eat Little Red Riding Hood because he is hungry and also because the story has to show something bad happening when children talk to strangers.",
        "Because he doesn't have enough time to eat her before Little Red Riding Hood arrives and can't let Little Red Riding Hood see both the wolf and the grandmother together or she will run for help.",
        "He helps Little Red Riding Hood in order to save her and her mother's lives.",
        "Because the killing is wrong and the lumberjack doesn't want to do a bad thing just because the wolf wanted to do a bad thing.",
        "The wolf is bad so that the story can show how talking to strangers can lead to bad things.",
        "She couldn't stop the wolf because if she did, then the story wouldn't be able to teach children not to talk to strangers.",
        "The wolf has to be able to talk so he can find out where Little Red Riding Hood's grandmother lives.",
        "The wolf doesn't have enough time to eat the grandmother before Little Red Riding Hood arrives and if she sees him trying to eat her grandmother, she'll run away and the wolf won't get her.",
        "All strangers aren't bad, but some are.  This story needs a bad stranger in it to show how if children talk to strangers, bad things can happen.",
        "Grown ups talk to strangers, but they need to be careful which strangers they talk to because bad things can happen to grown ups who talk to strangers, too.",
        "If the stranger is a bad person, he or she might use the infromation you give him to hurt you.",
        "The wolf has to know where the grandmother's house is.  Otherwise, the rest of the story doesn't make sense since the wolf wouldn't get to the grandmother's house.",
        "By realizing the lesson not to talk to strangers, Little Red Riding Hood helps other children learn the lesson, too.",
        "She had to go through the woods in order to get to her grandmother's house.",
        "The wolf grabbed her so quickly that she didn't have time to scream.",
        "The grandmother was expecting only Little Red Riding Hood to come, so she didn't expect any one else to come to her house.",
        "The story isn't true, but it is seems like it could be true to help children understand why it's bad to talk to strangers."]

    if s in l1:
        return l1.index(s)
    elif s in l2:
        return 0
    elif s in l3:
        return 1
    elif s in l4:
        return 2
    elif s in l5:
        return 3
    return -1

